# Generated by Django 3.1.7 on 2021-04-08 11:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('access_statistics', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='readnum',
            options={'ordering': ['-read_num'], 'verbose_name': '访问统计', 'verbose_name_plural': '访问统计'},
        ),
        migrations.AlterField(
            model_name='readnum',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype', verbose_name='统计模块'),
        ),
        migrations.AlterField(
            model_name='readnum',
            name='object_id',
            field=models.PositiveIntegerField(verbose_name='内容ID'),
        ),
        migrations.CreateModel(
            name='ReadDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object_id', models.PositiveIntegerField(verbose_name='内容ID')),
                ('read_num', models.IntegerField(default=0, verbose_name='阅读数')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='contenttypes.contenttype', verbose_name='统计模块')),
            ],
            options={
                'verbose_name': '访问统计详情',
                'verbose_name_plural': '访问统计详情',
            },
        ),
    ]
