# Generated by Django 3.1.7 on 2021-04-08 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20210408_1110'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadNum',
        ),
    ]
